datasources:
    datasources.yaml:
        apiVersion: 1
        datasources:
            -
                name: "Prometheus"
                type: "prometheus"
                access: "proxy"
                url: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
                jsonData:
                    httpMethod: "POST"
                    manageAlerts: true
                    prometheusType: "Prometheus"
                    prometheusVersion: 2.44.0
                    cacheLevel: "Low"

dashboardProviders:
    dashboardproviders.yaml:
        apiVersion: 1
        providers:
            - name: "default"
              orgId: 1
              folder: ""
              type: "file"
              disableDeletion: false
              editable: true
              options:
                  path: "/var/lib/grafana/dashboards/default"

dashboards:
    default:
        Kubernetes:
            # https://grafana:com/grafana/dashboards/315-kubernetes-cluster-monitoring-via-prometheus/
            gnetId: 315
            revision: 3
            datasource: "Prometheus"
